server:
  port: 30303

# spring 配置
spring:
  application:
    name: alinesno-infra-smart-media-boot
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_alinesno_infra_smart_media_v100?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: adminer
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local
  kafka:
    bootstrap-servers: 192.168.101.18:9092
    consumer:
      group-id: infra_logback

actable:
  table:
    auto: update
  model:
    pack: com.alinesno.infra.smart.media.entity
  database:
    type: mysql
  index:
    prefix: alinesno_smart_media_idx_
  unique:
    prefix: alinesno_smart_media_uni_

# sa-token配置
sa-token:
  token-name: satoken
  host-path: http://alinesno-infra-base-identity-auth-application.beta.base.infra.linesno.com
  sso:
    auth-url: ${sa-token.host-path}/login
    is-http: true
    check-ticket-url: ${sa-token.host-path}/sso/checkTicket
    slo-url: ${sa-token.host-path}/sso/signout
    get-data-url: ${sa-token.host-path}/sso/getData
  sign:
    secret-key: